/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlogFileType = IDL.Variant({
  'pdf' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const CharacterNoteFileType = IDL.Variant({
  'pdf' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'previewImage' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'fileType' : IDL.Opt(BlogFileType),
});
export const BookMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'coverImage' : ExternalBlob,
  'summary' : IDL.Text,
  'genre' : IDL.Text,
});
export const CharacterNote = IDL.Record({
  'id' : IDL.Text,
  'previewImage' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'bookId' : IDL.Text,
  'fileType' : IDL.Opt(CharacterNoteFileType),
});
export const NewComing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'releaseDate' : IDL.Opt(IDL.Text),
});
export const ForumReply = IDL.Record({
  'authorAvatar' : IDL.Opt(ExternalBlob),
  'authorId' : IDL.Principal,
  'authorName' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'replyId' : IDL.Text,
  'threadId' : IDL.Text,
});
export const ForumThread = IDL.Record({
  'title' : IDL.Text,
  'authorAvatar' : IDL.Opt(ExternalBlob),
  'authorId' : IDL.Principal,
  'authorName' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'replyCount' : IDL.Nat,
  'replies' : IDL.Vec(ForumReply),
  'threadId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'welcomeMessageShown' : IDL.Bool,
  'gender' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Opt(ExternalBlob),
  'bestReads' : IDL.Opt(IDL.Text),
});
export const BookFileType = IDL.Variant({
  'pdf' : IDL.Null,
  'wordDoc' : IDL.Null,
  'wordDocx' : IDL.Null,
});
export const BookAsset = IDL.Record({
  'id' : IDL.Text,
  'bookFile' : ExternalBlob,
  'fileType' : BookFileType,
  'coverImage' : ExternalBlob,
});
export const BookComment = IDL.Record({
  'userName' : IDL.Text,
  'likeCount' : IDL.Nat,
  'commentId' : IDL.Text,
  'userId' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BookRating = IDL.Record({
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const PublicUserProfile = IDL.Record({
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const SiteAssets = IDL.Record({
  'logo' : ExternalBlob,
  'authorPhoto' : ExternalBlob,
});
export const Suggestion = IDL.Record({
  'id' : IDL.Text,
  'authorAvatar' : IDL.Opt(ExternalBlob),
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(BlogFileType),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'addBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'addBookComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addBookRating' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addCharacterNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(CharacterNoteFileType),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'addNewComing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminLogout' : IDL.Func([], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'countRepliesByThread' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'createSuggestion' : IDL.Func([IDL.Text], [], []),
  'createThread' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'deleteCharacterNote' : IDL.Func([IDL.Text], [], []),
  'deleteNewComing' : IDL.Func([IDL.Text], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBooks' : IDL.Func([], [IDL.Vec(BookMetadata)], ['query']),
  'getAllCharacterNotes' : IDL.Func([], [IDL.Vec(CharacterNote)], ['query']),
  'getAllNewComings' : IDL.Func([], [IDL.Vec(NewComing)], ['query']),
  'getAllThreadsWithReplies' : IDL.Func([], [IDL.Vec(ForumThread)], ['query']),
  'getAllUserProfilesWithPrincipals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [IDL.Opt(BookMetadata)], ['query']),
  'getBookAssets' : IDL.Func([IDL.Text], [IDL.Opt(BookAsset)], ['query']),
  'getBookAverageRating' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getBookComments' : IDL.Func([IDL.Text], [IDL.Vec(BookComment)], ['query']),
  'getBookRatings' : IDL.Func([IDL.Text], [IDL.Vec(BookRating)], ['query']),
  'getBooksInFeaturedOrder' : IDL.Func([], [IDL.Vec(BookMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacterNote' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CharacterNote)],
      ['query'],
    ),
  'getCharacterNotesByBook' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CharacterNote)],
      ['query'],
    ),
  'getCommentLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getNewComing' : IDL.Func([IDL.Text], [IDL.Opt(NewComing)], ['query']),
  'getPublicUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getRepliesByThread' : IDL.Func([IDL.Text], [IDL.Vec(ForumReply)], ['query']),
  'getReplyById' : IDL.Func([IDL.Text], [IDL.Opt(ForumReply)], ['query']),
  'getSiteAssets' : IDL.Func([], [IDL.Opt(SiteAssets)], ['query']),
  'getSuggestionsFeed' : IDL.Func([], [IDL.Vec(Suggestion)], ['query']),
  'getThreadWithReplies' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ForumThread)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCurrentSessionAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeComment' : IDL.Func([IDL.Text], [], []),
  'replyToThread' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(BlogFileType),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'updateCharacterNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(CharacterNoteFileType),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateNewComing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'uploadAuthorPhoto' : IDL.Func([ExternalBlob], [], []),
  'uploadBookCover' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadBookFile' : IDL.Func([IDL.Text, ExternalBlob, BookFileType], [], []),
  'uploadLogo' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlogFileType = IDL.Variant({
    'pdf' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const CharacterNoteFileType = IDL.Variant({
    'pdf' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'previewImage' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'fileType' : IDL.Opt(BlogFileType),
  });
  const BookMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'coverImage' : ExternalBlob,
    'summary' : IDL.Text,
    'genre' : IDL.Text,
  });
  const CharacterNote = IDL.Record({
    'id' : IDL.Text,
    'previewImage' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'bookId' : IDL.Text,
    'fileType' : IDL.Opt(CharacterNoteFileType),
  });
  const NewComing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'releaseDate' : IDL.Opt(IDL.Text),
  });
  const ForumReply = IDL.Record({
    'authorAvatar' : IDL.Opt(ExternalBlob),
    'authorId' : IDL.Principal,
    'authorName' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'replyId' : IDL.Text,
    'threadId' : IDL.Text,
  });
  const ForumThread = IDL.Record({
    'title' : IDL.Text,
    'authorAvatar' : IDL.Opt(ExternalBlob),
    'authorId' : IDL.Principal,
    'authorName' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'replyCount' : IDL.Nat,
    'replies' : IDL.Vec(ForumReply),
    'threadId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'welcomeMessageShown' : IDL.Bool,
    'gender' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Opt(ExternalBlob),
    'bestReads' : IDL.Opt(IDL.Text),
  });
  const BookFileType = IDL.Variant({
    'pdf' : IDL.Null,
    'wordDoc' : IDL.Null,
    'wordDocx' : IDL.Null,
  });
  const BookAsset = IDL.Record({
    'id' : IDL.Text,
    'bookFile' : ExternalBlob,
    'fileType' : BookFileType,
    'coverImage' : ExternalBlob,
  });
  const BookComment = IDL.Record({
    'userName' : IDL.Text,
    'likeCount' : IDL.Nat,
    'commentId' : IDL.Text,
    'userId' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BookRating = IDL.Record({
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const PublicUserProfile = IDL.Record({
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const SiteAssets = IDL.Record({
    'logo' : ExternalBlob,
    'authorPhoto' : ExternalBlob,
  });
  const Suggestion = IDL.Record({
    'id' : IDL.Text,
    'authorAvatar' : IDL.Opt(ExternalBlob),
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(BlogFileType),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'addBookComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addBookRating' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addCharacterNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(CharacterNoteFileType),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addNewComing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminLogout' : IDL.Func([], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'countRepliesByThread' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'createSuggestion' : IDL.Func([IDL.Text], [], []),
    'createThread' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'deleteCharacterNote' : IDL.Func([IDL.Text], [], []),
    'deleteNewComing' : IDL.Func([IDL.Text], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBooks' : IDL.Func([], [IDL.Vec(BookMetadata)], ['query']),
    'getAllCharacterNotes' : IDL.Func([], [IDL.Vec(CharacterNote)], ['query']),
    'getAllNewComings' : IDL.Func([], [IDL.Vec(NewComing)], ['query']),
    'getAllThreadsWithReplies' : IDL.Func(
        [],
        [IDL.Vec(ForumThread)],
        ['query'],
      ),
    'getAllUserProfilesWithPrincipals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [IDL.Opt(BookMetadata)], ['query']),
    'getBookAssets' : IDL.Func([IDL.Text], [IDL.Opt(BookAsset)], ['query']),
    'getBookAverageRating' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getBookComments' : IDL.Func([IDL.Text], [IDL.Vec(BookComment)], ['query']),
    'getBookRatings' : IDL.Func([IDL.Text], [IDL.Vec(BookRating)], ['query']),
    'getBooksInFeaturedOrder' : IDL.Func(
        [],
        [IDL.Vec(BookMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacterNote' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CharacterNote)],
        ['query'],
      ),
    'getCharacterNotesByBook' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CharacterNote)],
        ['query'],
      ),
    'getCommentLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getNewComing' : IDL.Func([IDL.Text], [IDL.Opt(NewComing)], ['query']),
    'getPublicUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getRepliesByThread' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ForumReply)],
        ['query'],
      ),
    'getReplyById' : IDL.Func([IDL.Text], [IDL.Opt(ForumReply)], ['query']),
    'getSiteAssets' : IDL.Func([], [IDL.Opt(SiteAssets)], ['query']),
    'getSuggestionsFeed' : IDL.Func([], [IDL.Vec(Suggestion)], ['query']),
    'getThreadWithReplies' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ForumThread)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCurrentSessionAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeComment' : IDL.Func([IDL.Text], [], []),
    'replyToThread' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(BlogFileType),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'updateCharacterNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(CharacterNoteFileType),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateNewComing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'uploadAuthorPhoto' : IDL.Func([ExternalBlob], [], []),
    'uploadBookCover' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadBookFile' : IDL.Func([IDL.Text, ExternalBlob, BookFileType], [], []),
    'uploadLogo' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };