/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlogFileType = IDL.Variant({
  'pdf' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const CharacterNoteFileType = IDL.Variant({
  'pdf' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'previewImage' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'fileType' : IDL.Opt(BlogFileType),
});
export const CharacterNote = IDL.Record({
  'id' : IDL.Text,
  'previewImage' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'bookId' : IDL.Text,
  'fileType' : IDL.Opt(CharacterNoteFileType),
});
export const NewComing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'releaseDate' : IDL.Opt(IDL.Text),
});
export const BookFileType = IDL.Variant({
  'pdf' : IDL.Null,
  'wordDoc' : IDL.Null,
  'wordDocx' : IDL.Null,
});
export const BookAsset = IDL.Record({
  'id' : IDL.Text,
  'bookFile' : ExternalBlob,
  'fileType' : BookFileType,
  'coverImage' : ExternalBlob,
});
export const BookMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'coverImage' : ExternalBlob,
  'summary' : IDL.Text,
  'genre' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteAssets = IDL.Record({
  'logo' : ExternalBlob,
  'authorPhoto' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(BlogFileType),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'addBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'addCharacterNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(CharacterNoteFileType),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'addNewComing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'deleteCharacterNote' : IDL.Func([IDL.Text], [], []),
  'deleteNewComing' : IDL.Func([IDL.Text], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllCharacterNotes' : IDL.Func([], [IDL.Vec(CharacterNote)], ['query']),
  'getAllNewComings' : IDL.Func([], [IDL.Vec(NewComing)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBookAssets' : IDL.Func([IDL.Text], [IDL.Opt(BookAsset)], ['query']),
  'getBooksInFeaturedOrder' : IDL.Func([], [IDL.Vec(BookMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacterNote' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CharacterNote)],
      ['query'],
    ),
  'getNewComing' : IDL.Func([IDL.Text], [IDL.Opt(NewComing)], ['query']),
  'getSiteAssets' : IDL.Func([], [IDL.Opt(SiteAssets)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(BlogFileType),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'updateCharacterNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(CharacterNoteFileType),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateNewComing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'uploadBookCover' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadBookFile' : IDL.Func([IDL.Text, ExternalBlob, BookFileType], [], []),
  'uploadLogo' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlogFileType = IDL.Variant({
    'pdf' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const CharacterNoteFileType = IDL.Variant({
    'pdf' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'previewImage' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'fileType' : IDL.Opt(BlogFileType),
  });
  const CharacterNote = IDL.Record({
    'id' : IDL.Text,
    'previewImage' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'bookId' : IDL.Text,
    'fileType' : IDL.Opt(CharacterNoteFileType),
  });
  const NewComing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'releaseDate' : IDL.Opt(IDL.Text),
  });
  const BookFileType = IDL.Variant({
    'pdf' : IDL.Null,
    'wordDoc' : IDL.Null,
    'wordDocx' : IDL.Null,
  });
  const BookAsset = IDL.Record({
    'id' : IDL.Text,
    'bookFile' : ExternalBlob,
    'fileType' : BookFileType,
    'coverImage' : ExternalBlob,
  });
  const BookMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'coverImage' : ExternalBlob,
    'summary' : IDL.Text,
    'genre' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteAssets = IDL.Record({
    'logo' : ExternalBlob,
    'authorPhoto' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(BlogFileType),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'addCharacterNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(CharacterNoteFileType),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addNewComing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'deleteCharacterNote' : IDL.Func([IDL.Text], [], []),
    'deleteNewComing' : IDL.Func([IDL.Text], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllCharacterNotes' : IDL.Func([], [IDL.Vec(CharacterNote)], ['query']),
    'getAllNewComings' : IDL.Func([], [IDL.Vec(NewComing)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBookAssets' : IDL.Func([IDL.Text], [IDL.Opt(BookAsset)], ['query']),
    'getBooksInFeaturedOrder' : IDL.Func(
        [],
        [IDL.Vec(BookMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacterNote' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CharacterNote)],
        ['query'],
      ),
    'getNewComing' : IDL.Func([IDL.Text], [IDL.Opt(NewComing)], ['query']),
    'getSiteAssets' : IDL.Func([], [IDL.Opt(SiteAssets)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(BlogFileType),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'updateCharacterNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(CharacterNoteFileType),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateNewComing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'uploadBookCover' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadBookFile' : IDL.Func([IDL.Text, ExternalBlob, BookFileType], [], []),
    'uploadLogo' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };