/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlogFileType = { 'pdf' : null } |
  { 'video' : null } |
  { 'image' : null };
export interface BlogPost {
  'id' : string,
  'previewImage' : [] | [ExternalBlob],
  'title' : string,
  'file' : [] | [ExternalBlob],
  'description' : string,
  'fileType' : [] | [BlogFileType],
}
export interface BookAsset {
  'id' : string,
  'bookFile' : ExternalBlob,
  'fileType' : BookFileType,
  'coverImage' : ExternalBlob,
}
export type BookFileType = { 'pdf' : null } |
  { 'wordDoc' : null } |
  { 'wordDocx' : null };
export interface BookMetadata {
  'id' : string,
  'title' : string,
  'sortOrder' : bigint,
  'coverImage' : ExternalBlob,
  'summary' : string,
  'genre' : string,
}
export interface CharacterNote {
  'id' : string,
  'previewImage' : [] | [ExternalBlob],
  'title' : string,
  'file' : [] | [ExternalBlob],
  'description' : string,
  'bookId' : string,
  'fileType' : [] | [CharacterNoteFileType],
}
export type CharacterNoteFileType = { 'pdf' : null } |
  { 'video' : null } |
  { 'image' : null };
export type ExternalBlob = Uint8Array;
export interface NewComing {
  'id' : string,
  'title' : string,
  'sortOrder' : bigint,
  'description' : string,
  'image' : ExternalBlob,
  'releaseDate' : [] | [string],
}
export interface SiteAssets {
  'logo' : ExternalBlob,
  'authorPhoto' : ExternalBlob,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogPost' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [BlogFileType],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'addBook' : ActorMethod<
    [string, string, string, string, bigint, ExternalBlob],
    undefined
  >,
  'addCharacterNote' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [CharacterNoteFileType],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'addNewComing' : ActorMethod<
    [string, string, string, ExternalBlob, [] | [string], bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'deleteCharacterNote' : ActorMethod<[string], undefined>,
  'deleteNewComing' : ActorMethod<[string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllCharacterNotes' : ActorMethod<[], Array<CharacterNote>>,
  'getAllNewComings' : ActorMethod<[], Array<NewComing>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBookAssets' : ActorMethod<[string], [] | [BookAsset]>,
  'getBooksInFeaturedOrder' : ActorMethod<[], Array<BookMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacterNote' : ActorMethod<[string], [] | [CharacterNote]>,
  'getNewComing' : ActorMethod<[string], [] | [NewComing]>,
  'getSiteAssets' : ActorMethod<[], [] | [SiteAssets]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBlogPost' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [BlogFileType],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'updateBook' : ActorMethod<
    [string, string, string, string, bigint, ExternalBlob],
    undefined
  >,
  'updateCharacterNote' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [CharacterNoteFileType],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'updateNewComing' : ActorMethod<
    [string, string, string, ExternalBlob, [] | [string], bigint],
    undefined
  >,
  'uploadBookCover' : ActorMethod<[string, ExternalBlob], undefined>,
  'uploadBookFile' : ActorMethod<
    [string, ExternalBlob, BookFileType],
    undefined
  >,
  'uploadLogo' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];