/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BookAsset {
    id: string;
    bookFile: ExternalBlob;
    fileType: BookFileType;
    coverImage: ExternalBlob;
}
export interface BlogPost {
    id: string;
    previewImage?: ExternalBlob;
    title: string;
    file?: ExternalBlob;
    description: string;
    fileType?: BlogFileType;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Suggestion {
    id: string;
    authorAvatar?: ExternalBlob;
    authorName: string;
    author: Principal;
    message: string;
    timestamp: bigint;
}
export interface ForumReply {
    authorAvatar?: ExternalBlob;
    authorId: Principal;
    authorName: string;
    message: string;
    timestamp: bigint;
    replyId: string;
    threadId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CharacterNote {
    id: string;
    previewImage?: ExternalBlob;
    title: string;
    file?: ExternalBlob;
    description: string;
    bookId: string;
    fileType?: CharacterNoteFileType;
}
export interface ForumThread {
    title: string;
    authorAvatar?: ExternalBlob;
    authorId: Principal;
    authorName: string;
    message: string;
    timestamp: bigint;
    replyCount: bigint;
    replies: Array<ForumReply>;
    threadId: string;
}
export interface BookRating {
    userName: string;
    userId: Principal;
    timestamp: bigint;
    rating: bigint;
}
export interface BookComment {
    userName: string;
    likeCount: bigint;
    commentId: string;
    userId: Principal;
    comment: string;
    timestamp: bigint;
}
export interface PublicUserProfile {
    name: string;
    profilePicture?: ExternalBlob;
}
export interface SiteAssets {
    logo: ExternalBlob;
    authorPhoto: ExternalBlob;
}
export interface BookMetadata {
    id: string;
    title: string;
    sortOrder: bigint;
    coverImage: ExternalBlob;
    summary: string;
    genre: string;
}
export interface NewComing {
    id: string;
    title: string;
    sortOrder: bigint;
    description: string;
    image: ExternalBlob;
    releaseDate?: string;
}
export interface UserProfile {
    name: string;
    email: string;
    welcomeMessageShown: boolean;
    gender?: string;
    profilePicture?: ExternalBlob;
    bestReads?: string;
}
export enum BookFileType {
    pdf = "pdf",
    wordDoc = "wordDoc",
    wordDocx = "wordDocx"
}
export enum CharacterNoteFileType {
    pdf = "pdf",
    video = "video",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBlogPost(id: string, title: string, description: string, file: ExternalBlob | null, fileType: BlogFileType | null, previewImage: ExternalBlob | null): Promise<void>;
    addBook(id: string, title: string, summary: string, genre: string, sortOrder: bigint, coverImage: ExternalBlob): Promise<void>;
    addBookComment(bookId: string, comment: string): Promise<void>;
    addBookRating(bookId: string, rating: bigint): Promise<void>;
    addCharacterNote(id: string, bookId: string, title: string, description: string, file: ExternalBlob | null, fileType: CharacterNoteFileType | null, previewImage: ExternalBlob | null): Promise<void>;
    addNewComing(id: string, title: string, description: string, image: ExternalBlob, releaseDate: string | null, sortOrder: bigint): Promise<void>;
    adminLogin(username: string, password: string): Promise<boolean>;
    adminLogout(): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkProfileComplete(): Promise<boolean>;
    countRepliesByThread(threadId: string): Promise<bigint>;
    createSuggestion(message: string): Promise<void>;
    createThread(title: string, message: string): Promise<void>;
    deleteBlogPost(id: string): Promise<void>;
    deleteBook(id: string): Promise<void>;
    deleteCharacterNote(id: string): Promise<void>;
    deleteNewComing(id: string): Promise<void>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllBooks(): Promise<Array<BookMetadata>>;
    getAllCharacterNotes(): Promise<Array<CharacterNote>>;
    getAllNewComings(): Promise<Array<NewComing>>;
    getAllThreadsWithReplies(): Promise<Array<ForumThread>>;
    getAllUserProfilesWithPrincipals(): Promise<Array<[Principal, UserProfile]>>;
    getBlogPost(id: string): Promise<BlogPost | null>;
    getBook(id: string): Promise<BookMetadata | null>;
    getBookAssets(bookId: string): Promise<BookAsset | null>;
    getBookAverageRating(bookId: string): Promise<number | null>;
    getBookComments(bookId: string): Promise<Array<BookComment>>;
    getBookRatings(bookId: string): Promise<Array<BookRating>>;
    getBooksInFeaturedOrder(): Promise<Array<BookMetadata>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCharacterNote(id: string): Promise<CharacterNote | null>;
    getCharacterNotesByBook(bookId: string): Promise<Array<CharacterNote>>;
    getCommentLikeCount(commentId: string): Promise<bigint>;
    getNewComing(id: string): Promise<NewComing | null>;
    getPublicUserProfile(user: Principal): Promise<PublicUserProfile | null>;
    getRepliesByThread(threadId: string): Promise<Array<ForumReply>>;
    getReplyById(replyId: string): Promise<ForumReply | null>;
    getSiteAssets(): Promise<SiteAssets | null>;
    getSuggestionsFeed(): Promise<Array<Suggestion>>;
    getThreadWithReplies(threadId: string): Promise<ForumThread | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCurrentSessionAdmin(): Promise<boolean>;
    likeComment(commentId: string): Promise<void>;
    replyToThread(threadId: string, message: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBlogPost(id: string, title: string, description: string, file: ExternalBlob | null, fileType: BlogFileType | null, previewImage: ExternalBlob | null): Promise<void>;
    updateBook(id: string, title: string, summary: string, genre: string, sortOrder: bigint, coverImage: ExternalBlob): Promise<void>;
    updateCharacterNote(id: string, bookId: string, title: string, description: string, file: ExternalBlob | null, fileType: CharacterNoteFileType | null, previewImage: ExternalBlob | null): Promise<void>;
    updateNewComing(id: string, title: string, description: string, image: ExternalBlob, releaseDate: string | null, sortOrder: bigint): Promise<void>;
    uploadAuthorPhoto(photo: ExternalBlob): Promise<void>;
    uploadBookCover(bookId: string, image: ExternalBlob): Promise<void>;
    uploadBookFile(bookId: string, file: ExternalBlob, fileType: BookFileType): Promise<void>;
    uploadLogo(logo: ExternalBlob): Promise<void>;
}
import type { BlogFileType as _BlogFileType, BlogPost as _BlogPost, BookAsset as _BookAsset, BookFileType as _BookFileType, BookMetadata as _BookMetadata, CharacterNote as _CharacterNote, CharacterNoteFileType as _CharacterNoteFileType, ExternalBlob as _ExternalBlob, ForumReply as _ForumReply, ForumThread as _ForumThread, NewComing as _NewComing, PublicUserProfile as _PublicUserProfile, SiteAssets as _SiteAssets, Suggestion as _Suggestion, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBlogPost(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null, arg4: BlogFileType | null, arg5: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addBook(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addBookComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookComment(arg0, arg1);
            return result;
        }
    }
    async addBookRating(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookRating(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookRating(arg0, arg1);
            return result;
        }
    }
    async addCharacterNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob | null, arg5: CharacterNoteFileType | null, arg6: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCharacterNote(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCharacterNote(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addNewComing(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: string | null, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewComing(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewComing(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async adminLogout(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkProfileComplete(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkProfileComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkProfileComplete();
            return result;
        }
    }
    async countRepliesByThread(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countRepliesByThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countRepliesByThread(arg0);
            return result;
        }
    }
    async createSuggestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSuggestion(arg0);
            return result;
        }
    }
    async createThread(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createThread(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createThread(arg0, arg1);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteBook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async deleteCharacterNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCharacterNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCharacterNote(arg0);
            return result;
        }
    }
    async deleteNewComing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewComing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewComing(arg0);
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBooks(): Promise<Array<BookMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooks();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooks();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCharacterNotes(): Promise<Array<CharacterNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCharacterNotes();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCharacterNotes();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewComings(): Promise<Array<NewComing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewComings();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewComings();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllThreadsWithReplies(): Promise<Array<ForumThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllThreadsWithReplies();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllThreadsWithReplies();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfilesWithPrincipals(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfilesWithPrincipals();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfilesWithPrincipals();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBook(arg0: string): Promise<BookMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookAssets(arg0: string): Promise<BookAsset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookAssets(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookAssets(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookAverageRating(arg0: string): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookAverageRating(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookAverageRating(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookComments(arg0: string): Promise<Array<BookComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookComments(arg0);
            return result;
        }
    }
    async getBookRatings(arg0: string): Promise<Array<BookRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookRatings(arg0);
            return result;
        }
    }
    async getBooksInFeaturedOrder(): Promise<Array<BookMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooksInFeaturedOrder();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooksInFeaturedOrder();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacterNote(arg0: string): Promise<CharacterNote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacterNote(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacterNote(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacterNotesByBook(arg0: string): Promise<Array<CharacterNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacterNotesByBook(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacterNotesByBook(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentLikeCount(arg0);
            return result;
        }
    }
    async getNewComing(arg0: string): Promise<NewComing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewComing(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewComing(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicUserProfile(arg0: Principal): Promise<PublicUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicUserProfile(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicUserProfile(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepliesByThread(arg0: string): Promise<Array<ForumReply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepliesByThread(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepliesByThread(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReplyById(arg0: string): Promise<ForumReply | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplyById(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplyById(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteAssets(): Promise<SiteAssets | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteAssets();
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteAssets();
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuggestionsFeed(): Promise<Array<Suggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestionsFeed();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestionsFeed();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThreadWithReplies(arg0: string): Promise<ForumThread | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThreadWithReplies(arg0);
                return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThreadWithReplies(arg0);
            return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCurrentSessionAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCurrentSessionAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCurrentSessionAdmin();
            return result;
        }
    }
    async likeComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeComment(arg0);
            return result;
        }
    }
    async replyToThread(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToThread(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToThread(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n72(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n72(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBlogPost(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null, arg4: BlogFileType | null, arg5: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateBook(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateCharacterNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob | null, arg5: CharacterNoteFileType | null, arg6: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCharacterNote(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCharacterNote(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateNewComing(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: string | null, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewComing(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewComing(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async uploadAuthorPhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAuthorPhoto(await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAuthorPhoto(await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadBookCover(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBookCover(arg0, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBookCover(arg0, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadBookFile(arg0: string, arg1: ExternalBlob, arg2: BookFileType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBookFile(arg0, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg1), to_candid_BookFileType_n74(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBookFile(arg0, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg1), to_candid_BookFileType_n74(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async uploadLogo(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadLogo(await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadLogo(await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BlogFileType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogFileType): BlogFileType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_BlogPost_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_BookAsset_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookAsset): Promise<BookAsset> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_BookFileType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookFileType): BookFileType {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
async function from_candid_BookMetadata_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookMetadata): Promise<BookMetadata> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_CharacterNoteFileType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CharacterNoteFileType): CharacterNoteFileType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_CharacterNote_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CharacterNote): Promise<CharacterNote> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ForumReply_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ForumReply): Promise<ForumReply> {
    return await from_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_ForumThread_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ForumThread): Promise<ForumThread> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_NewComing_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewComing): Promise<NewComing> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_PublicUserProfile_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUserProfile): Promise<PublicUserProfile> {
    return await from_candid_record_n63(_uploadFile, _downloadFile, value);
}
async function from_candid_SiteAssets_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteAssets): Promise<SiteAssets> {
    return await from_candid_record_n67(_uploadFile, _downloadFile, value);
}
async function from_candid_Suggestion_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Suggestion): Promise<Suggestion> {
    return await from_candid_record_n70(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogFileType]): BlogFileType | null {
    return value.length === 0 ? null : from_candid_BlogFileType_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CharacterNoteFileType]): CharacterNoteFileType | null {
    return value.length === 0 ? null : from_candid_CharacterNoteFileType_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookMetadata]): Promise<BookMetadata | null> {
    return value.length === 0 ? null : await from_candid_BookMetadata_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookAsset]): Promise<BookAsset | null> {
    return value.length === 0 ? null : await from_candid_BookAsset_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n46(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CharacterNote]): Promise<CharacterNote | null> {
    return value.length === 0 ? null : await from_candid_CharacterNote_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewComing]): Promise<NewComing | null> {
    return value.length === 0 ? null : await from_candid_NewComing_n35(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUserProfile]): Promise<PublicUserProfile | null> {
    return value.length === 0 ? null : await from_candid_PublicUserProfile_n62(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ForumReply]): Promise<ForumReply | null> {
    return value.length === 0 ? null : await from_candid_ForumReply_n42(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SiteAssets]): Promise<SiteAssets | null> {
    return value.length === 0 ? null : await from_candid_SiteAssets_n66(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ForumThread]): Promise<ForumThread | null> {
    return value.length === 0 ? null : await from_candid_ForumThread_n39(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    previewImage: [] | [_ExternalBlob];
    title: string;
    file: [] | [_ExternalBlob];
    description: string;
    fileType: [] | [_BlogFileType];
}): Promise<{
    id: string;
    previewImage?: ExternalBlob;
    title: string;
    file?: ExternalBlob;
    description: string;
    fileType?: BlogFileType;
}> {
    return {
        id: value.id,
        previewImage: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.previewImage)),
        title: value.title,
        file: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.file)),
        description: value.description,
        fileType: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.fileType))
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    sortOrder: bigint;
    coverImage: _ExternalBlob;
    summary: string;
    genre: string;
}): Promise<{
    id: string;
    title: string;
    sortOrder: bigint;
    coverImage: ExternalBlob;
    summary: string;
    genre: string;
}> {
    return {
        id: value.id,
        title: value.title,
        sortOrder: value.sortOrder,
        coverImage: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.coverImage),
        summary: value.summary,
        genre: value.genre
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    previewImage: [] | [_ExternalBlob];
    title: string;
    file: [] | [_ExternalBlob];
    description: string;
    bookId: string;
    fileType: [] | [_CharacterNoteFileType];
}): Promise<{
    id: string;
    previewImage?: ExternalBlob;
    title: string;
    file?: ExternalBlob;
    description: string;
    bookId: string;
    fileType?: CharacterNoteFileType;
}> {
    return {
        id: value.id,
        previewImage: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.previewImage)),
        title: value.title,
        file: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.file)),
        description: value.description,
        bookId: value.bookId,
        fileType: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.fileType))
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    sortOrder: bigint;
    description: string;
    image: _ExternalBlob;
    releaseDate: [] | [string];
}): Promise<{
    id: string;
    title: string;
    sortOrder: bigint;
    description: string;
    image: ExternalBlob;
    releaseDate?: string;
}> {
    return {
        id: value.id,
        title: value.title,
        sortOrder: value.sortOrder,
        description: value.description,
        image: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.image),
        releaseDate: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.releaseDate))
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    authorAvatar: [] | [_ExternalBlob];
    authorId: Principal;
    authorName: string;
    message: string;
    timestamp: bigint;
    replyCount: bigint;
    replies: Array<_ForumReply>;
    threadId: string;
}): Promise<{
    title: string;
    authorAvatar?: ExternalBlob;
    authorId: Principal;
    authorName: string;
    message: string;
    timestamp: bigint;
    replyCount: bigint;
    replies: Array<ForumReply>;
    threadId: string;
}> {
    return {
        title: value.title,
        authorAvatar: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.authorAvatar)),
        authorId: value.authorId,
        authorName: value.authorName,
        message: value.message,
        timestamp: value.timestamp,
        replyCount: value.replyCount,
        replies: await from_candid_vec_n41(_uploadFile, _downloadFile, value.replies),
        threadId: value.threadId
    };
}
async function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    authorAvatar: [] | [_ExternalBlob];
    authorId: Principal;
    authorName: string;
    message: string;
    timestamp: bigint;
    replyId: string;
    threadId: string;
}): Promise<{
    authorAvatar?: ExternalBlob;
    authorId: Principal;
    authorName: string;
    message: string;
    timestamp: bigint;
    replyId: string;
    threadId: string;
}> {
    return {
        authorAvatar: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.authorAvatar)),
        authorId: value.authorId,
        authorName: value.authorName,
        message: value.message,
        timestamp: value.timestamp,
        replyId: value.replyId,
        threadId: value.threadId
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    welcomeMessageShown: boolean;
    gender: [] | [string];
    profilePicture: [] | [_ExternalBlob];
    bestReads: [] | [string];
}): Promise<{
    name: string;
    email: string;
    welcomeMessageShown: boolean;
    gender?: string;
    profilePicture?: ExternalBlob;
    bestReads?: string;
}> {
    return {
        name: value.name,
        email: value.email,
        welcomeMessageShown: value.welcomeMessageShown,
        gender: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.gender)),
        profilePicture: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePicture)),
        bestReads: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.bestReads))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bookFile: _ExternalBlob;
    fileType: _BookFileType;
    coverImage: _ExternalBlob;
}): Promise<{
    id: string;
    bookFile: ExternalBlob;
    fileType: BookFileType;
    coverImage: ExternalBlob;
}> {
    return {
        id: value.id,
        bookFile: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.bookFile),
        fileType: from_candid_BookFileType_n53(_uploadFile, _downloadFile, value.fileType),
        coverImage: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.coverImage)
    };
}
async function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    profilePicture?: ExternalBlob;
}> {
    return {
        name: value.name,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePicture))
    };
}
async function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logo: _ExternalBlob;
    authorPhoto: _ExternalBlob;
}): Promise<{
    logo: ExternalBlob;
    authorPhoto: ExternalBlob;
}> {
    return {
        logo: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.logo),
        authorPhoto: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.authorPhoto)
    };
}
async function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    authorAvatar: [] | [_ExternalBlob];
    authorName: string;
    author: Principal;
    message: string;
    timestamp: bigint;
}): Promise<{
    id: string;
    authorAvatar?: ExternalBlob;
    authorName: string;
    author: Principal;
    message: string;
    timestamp: bigint;
}> {
    return {
        id: value.id,
        authorAvatar: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.authorAvatar)),
        authorName: value.authorName,
        author: value.author,
        message: value.message,
        timestamp: value.timestamp
    };
}
async function from_candid_tuple_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): Promise<[Principal, UserProfile]> {
    return [
        value[0],
        await from_candid_UserProfile_n46(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    video: null;
} | {
    image: null;
}): CharacterNoteFileType {
    return "pdf" in value ? CharacterNoteFileType.pdf : "video" in value ? CharacterNoteFileType.video : "image" in value ? CharacterNoteFileType.image : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    wordDoc: null;
} | {
    wordDocx: null;
}): BookFileType {
    return "pdf" in value ? BookFileType.pdf : "wordDoc" in value ? BookFileType.wordDoc : "wordDocx" in value ? BookFileType.wordDocx : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookMetadata>): Promise<Array<BookMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BookMetadata_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CharacterNote>): Promise<Array<CharacterNote>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CharacterNote_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewComing>): Promise<Array<NewComing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NewComing_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ForumThread>): Promise<Array<ForumThread>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ForumThread_n39(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ForumReply>): Promise<Array<ForumReply>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ForumReply_n42(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Promise<Array<[Principal, UserProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n45(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Suggestion>): Promise<Array<Suggestion>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Suggestion_n69(_uploadFile, _downloadFile, x)));
}
function to_candid_BlogFileType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogFileType): _BlogFileType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_BookFileType_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookFileType): _BookFileType {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_CharacterNoteFileType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CharacterNoteFileType): _CharacterNoteFileType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UserProfile_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogFileType | null): [] | [_BlogFileType] {
    return value === null ? candid_none() : candid_some(to_candid_BlogFileType_n11(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CharacterNoteFileType | null): [] | [_CharacterNoteFileType] {
    return value === null ? candid_none() : candid_some(to_candid_CharacterNoteFileType_n14(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    welcomeMessageShown: boolean;
    gender?: string;
    profilePicture?: ExternalBlob;
    bestReads?: string;
}): Promise<{
    name: string;
    email: string;
    welcomeMessageShown: boolean;
    gender: [] | [string];
    profilePicture: [] | [_ExternalBlob];
    bestReads: [] | [string];
}> {
    return {
        name: value.name,
        email: value.email,
        welcomeMessageShown: value.welcomeMessageShown,
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        bestReads: value.bestReads ? candid_some(value.bestReads) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CharacterNoteFileType): {
    pdf: null;
} | {
    video: null;
} | {
    image: null;
} {
    return value == CharacterNoteFileType.pdf ? {
        pdf: null
    } : value == CharacterNoteFileType.video ? {
        video: null
    } : value == CharacterNoteFileType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookFileType): {
    pdf: null;
} | {
    wordDoc: null;
} | {
    wordDocx: null;
} {
    return value == BookFileType.pdf ? {
        pdf: null
    } : value == BookFileType.wordDoc ? {
        wordDoc: null
    } : value == BookFileType.wordDocx ? {
        wordDocx: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
